# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a9d3ae260912edfdfb9937c2a6d8148"
application_url = "https://vcom-reviews-production.up.railway.app"
embedded = true
name = "vcom reviwers"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
scopes = "read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_files,write_files,read_products,read_themes"

[auth]
redirect_urls = [
  "https://vcom-reviews-production.up.railway.app/auth/callback",
  "https://vcom-reviews-production.up.railway.app/auth/shopify/callback",
]

[pos]
embedded = false

[app_proxy]
url = "https://vcom-reviews-production.up.railway.app/app_proxy"
subpath = "vcom-reviews"
prefix = "apps"
